/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "Auth": {
        "region": "us-east-1",
        "userPoolId": "us-east-1_fxqdGPnnZ",
        "userPoolWebClientId": "49gf14snt2hgr0p4grf9slkcuq"
    }
};


export default awsmobile;
